#!/bin/bash

configdir=$(couch-config --config-dir)
dbdir=$(couch-config --db-dir)

echo Deleting $configdir and $dbdir.
rm -Rf $configdir $dbdir

if [[ $(uname) == 'Linux' ]]; then
  if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 
    exit 1
  fi
  apt-get --assume-yes purge couchdb
  apt-get --assume-yes install couchdb
elif [[ $(uname) == 'Darwin' ]]; then
  brew uninstall couchdb
  brew install couchdb
fi
